"""Coding-trainer API — user state only.

The knowledge content is NOT served from here: it is static JSON under
app/public/data (generated by build_content.py) that the browser fetches and
indexes into its own in-memory SQLite. What is left is the state that content
can't be: saved code, test runs and timed attempts, held in DynamoDB and read
through /api/progress and /api/problem/state.

POST /api/problem/runs is the one piece of real domain logic still on the
server: it derives all_passed and finalizes the solve on the server clock.

Problems are identified by their path-based id (e.g. "maximum-subarray" or
"CTCI/1.1-is-unique"). Ids can contain "/", so id-specific endpoints take the id
as a query parameter or request-body field rather than a path segment.
"""

import re
from contextlib import asynccontextmanager
from datetime import datetime, timezone

import db
from fastapi import Depends, FastAPI, HTTPException, Request
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel


@asynccontextmanager
async def lifespan(_app: FastAPI):
  db.init_db()
  yield


app = FastAPI(title="Coding Trainer API", lifespan=lifespan)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


def now_iso() -> str:
  return datetime.now(timezone.utc).isoformat()


# --- who the state belongs to ----------------------------------------------

USER_COOKIE = "trainer_uid"

# The cookie value goes straight into a DynamoDB partition key, so it is
# constrained to exactly the shape the frontend writes — crypto.randomUUID() —
# and anything else is refused before it can reach a key.
_USER_ID_RE = re.compile(
    r"\A[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\Z", re.I
)


def current_user(request: Request) -> str:
  """The id whose state this request reads and writes.

  THIS IS NOT AUTHENTICATION. The id is generated in the browser and rides in a
  cookie that is deliberately not HttpOnly (the frontend has to be able to
  create it), so anyone can set it to someone else's id and read their data. It
  is a partition key for a single-user prototype and nothing may be built on top
  of it that assumes otherwise. When real auth arrives this function reads a
  verified token claim instead and no other code changes — every endpoint
  resolves the user here and only here.

  A missing or malformed cookie is a 400 rather than a fallback: the frontend
  sets it before its first fetch, so the only callers that get here without one
  are scripts, and quietly pooling them into a shared partition would be a
  worse answer than a loud one.
  """
  raw = request.cookies.get(USER_COOKIE, "")
  if not _USER_ID_RE.match(raw):
    raise HTTPException(
        status_code=400, detail=f"missing or malformed {USER_COOKIE} cookie"
    )
  return raw.lower()


UserId = Depends(current_user)


def checked_id(pid: str) -> str:
  """Problem ids are client-supplied too, and they land in the sort key.

  "#" is the separator of the RUN#/SLV# keys, so an id containing one could make
  a Query's begins_with prefix match another problem's items.
  """
  if not pid or len(pid) > 200 or "#" in pid:
    raise HTTPException(status_code=400, detail="invalid problem id")
  return pid


class CodePayload(BaseModel):
  id: str
  code: str


class RunPayload(BaseModel):
  id: str
  code: str
  passed: int
  failed: int
  total: int
  durationMs: float


def _run_dict(r) -> dict:
  return {
      "id": r["id"],
      "problemId": r["problem_id"],
      "passed": r["passed"],
      "failed": r["failed"],
      "total": r["total"],
      "durationMs": r["duration_ms"],
      "allPassed": bool(r["all_passed"]),
      "createdAt": r["created_at"],
      "code": r["code"],
  }


@app.get("/api/health")
def health():
  return {"ok": True}


# --- attempts / timing ---


def _now_dt() -> datetime:
  return datetime.now(timezone.utc)


def _delta_ms(iso: str, now: datetime) -> float:
  return (now - datetime.fromisoformat(iso)).total_seconds() * 1000


def _attempt_fields(a) -> dict:
  """Status + timing from the latest attempt.

  `a` is the problem's state row, or None when the user has none for it. A row
  whose started_at is unset means "has other state (saved code, or runs) but was
  never started", which is still not-started. This is the single source of truth
  for the derived status; the client's `progress` table stores what this returns
  and never re-derives it.
  """
  if a is None or a["started_at"] is None:
    return {
        "status": "not-started",
        "startedAt": None,
        "accumulatedMs": 0,
        "runningSince": None,
        "solvedAt": None,
        "elapsedMs": None,
    }
  return {
      "status": "solved" if a["solved_at"] else "started",
      "startedAt": a["started_at"],
      "accumulatedMs": a["accumulated_ms"],
      "runningSince": a["running_since"],
      "solvedAt": a["solved_at"],
      "elapsedMs": a["elapsed_ms"],
  }


# --- user state ---


def _progress_entry(pid, a, attempt_run_count, run_count, solves) -> dict:
  """One problem's dynamic state. The client joins this onto the static catalog.

  `solves` is EVERY solved attempt (ascending), not just the latest: the stats
  minimum-elapsed fold, the stats per-day sets and lesson "ever solved" all need
  more than the latest attempt (after a Retake the latest attempt is unsolved,
  but the lesson must stay complete).
  """
  return {
      "id": pid,
      **_attempt_fields(a),
      "attemptRunCount": attempt_run_count,
      "runCount": run_count,
      "solves": solves,
  }


def _solves_by_problem(rows) -> dict:
  by_id = {}
  for r in rows:
    by_id.setdefault(r["problem_id"], []).append(
        {"solvedAt": r["solved_at"], "elapsedMs": r["elapsed_ms"]}
    )
  return by_id


@app.get("/api/progress")
def progress(user_id: str = UserId):
  """Every problem's dynamic state, in one bundle (two queries, no N+1).

  Includes problems that have runs but were never started, and ids that are no
  longer in the catalog — both are deliberate. Problems whose only state is
  autosaved code are excluded: autosave writes on every keystroke, and a problem
  the user merely typed in is not progress.
  """
  states = db.list_problems(user_id)
  solves = _solves_by_problem(db.list_solves(user_id))
  items = [
      _progress_entry(s["problem_id"], s, s["attempt_run_count"], s["run_count"],
                      solves.get(s["problem_id"], []))
      for s in states
      if s["started_at"] or s["run_count"]
  ]
  return {"problems": items}


@app.get("/api/problem/state")
def problem_state(id: str, user_id: str = UserId):
  """One problem's dynamic state + its saved code.

  Never 404s: whether an id exists is now a *content* question, answered by
  catalog.json. An unknown id is simply not-started with no code.
  """
  pid = checked_id(id)
  s = db.get_problem(user_id, pid)
  solves = _solves_by_problem(db.list_solves(user_id, pid))
  entry = _progress_entry(
      pid, s, s["attempt_run_count"] if s else 0,
      s["run_count"] if s else 0, solves.get(pid, []),
  )
  return {**entry, "code": s["code"] if s else None}


@app.post("/api/problem/attempt/start")
def start_attempt(id: str, user_id: str = UserId):
  """Start (or Retake) — reset the timer fields to a fresh running attempt."""
  db.start_attempt(user_id, checked_id(id), now_iso())
  return {"ok": True}


@app.post("/api/problem/attempt/pause")
def pause_attempt(id: str, user_id: str = UserId):
  pid = checked_id(id)
  a = db.get_problem(user_id, pid)
  if a and a["running_since"] and a["solved_at"] is None:
    add = round(_delta_ms(a["running_since"], _now_dt()))
    db.pause_attempt(user_id, pid, add)
  return {"ok": True}


@app.post("/api/problem/attempt/resume")
def resume_attempt(id: str, user_id: str = UserId):
  pid = checked_id(id)
  a = db.get_problem(user_id, pid)
  if a and a["started_at"] and a["running_since"] is None and a["solved_at"] is None:
    db.resume_attempt(user_id, pid, now_iso())
  return {"ok": True}


@app.put("/api/problem/code")
def save_code(payload: CodePayload, user_id: str = UserId):
  ts = now_iso()
  db.save_code(user_id, checked_id(payload.id), payload.code, ts)
  return {"ok": True, "updatedAt": ts}


@app.get("/api/problem/runs")
def list_runs(id: str, limit: int = 50, user_id: str = UserId):
  # DynamoDB rejects a Limit below 1, where SQLite happily took LIMIT 0; keep
  # the empty answer rather than turning it into a 500.
  if limit < 1:
    return []
  return [_run_dict(r) for r in db.list_runs(user_id, checked_id(id), min(limit, 1000))]


@app.post("/api/problem/runs")
def create_run(payload: RunPayload, user_id: str = UserId):
  pid = checked_id(payload.id)
  all_passed = 1 if payload.failed == 0 and payload.total > 0 else 0
  ts = now_iso()
  a = db.get_problem(user_id, pid)
  in_attempt = bool(a and a["started_at"])
  run = db.create_run(
      user_id, pid, payload.code, payload.passed, payload.failed,
      payload.total, payload.durationMs, all_passed, ts, in_attempt,
  )
  # Finalize the solve time on the active attempt.
  if all_passed and a and a["started_at"] and a["solved_at"] is None:
    extra = round(_delta_ms(a["running_since"], _now_dt())) if a["running_since"] else 0
    db.finalize_solve(user_id, pid, ts, a["accumulated_ms"] + extra)
  return _run_dict(run)
