"""Coding-trainer API — user state only.

No auth (single implicit user). The knowledge content is NOT served from here:
it is static JSON under app/public/data (generated by build_content.py) that the
browser fetches and indexes into its own in-memory SQLite. What is left is the
state that content can't be: saved code, test runs and timed attempts, read
through /api/progress and /api/problem/state and written by the endpoints below.

POST /api/problem/runs is the one piece of real domain logic still on the
server: it derives all_passed and finalizes the solve on the server clock.

Problems are identified by their path-based id (e.g. "maximum-subarray" or
"CTCI/1.1-is-unique"). Ids can contain "/", so id-specific endpoints take the id
as a query parameter or request-body field rather than a path segment.
"""

from contextlib import asynccontextmanager
from datetime import datetime, timezone

import db
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel


@asynccontextmanager
async def lifespan(_app: FastAPI):
  db.init_db()
  yield


app = FastAPI(title="Coding Trainer API", lifespan=lifespan)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


def now_iso() -> str:
  return datetime.now(timezone.utc).isoformat()


class CodePayload(BaseModel):
  id: str
  code: str


class RunPayload(BaseModel):
  id: str
  code: str
  passed: int
  failed: int
  total: int
  durationMs: float


def _run_dict(r) -> dict:
  return {
      "id": r["id"],
      "problemId": r["problem_id"],
      "passed": r["passed"],
      "failed": r["failed"],
      "total": r["total"],
      "durationMs": r["duration_ms"],
      "allPassed": bool(r["all_passed"]),
      "createdAt": r["created_at"],
      "code": r["code"],
  }


@app.get("/api/health")
def health():
  return {"ok": True}


# --- attempts / timing ---


def _now_dt() -> datetime:
  return datetime.now(timezone.utc)


def _delta_ms(iso: str, now: datetime) -> float:
  return (now - datetime.fromisoformat(iso)).total_seconds() * 1000


def _attempt_fields(a) -> dict:
  """Status + timing from the latest attempt.

  `a` is either the latest attempt row or None (no attempt) — the latter means
  "not-started". This is the single source of truth for the derived status; the
  client's `progress` table stores what this returns and never re-derives it.
  """
  if a is None or a["started_at"] is None:
    return {
        "status": "not-started",
        "startedAt": None,
        "accumulatedMs": 0,
        "runningSince": None,
        "solvedAt": None,
        "elapsedMs": None,
    }
  return {
      "status": "solved" if a["solved_at"] else "started",
      "startedAt": a["started_at"],
      "accumulatedMs": a["accumulated_ms"],
      "runningSince": a["running_since"],
      "solvedAt": a["solved_at"],
      "elapsedMs": a["elapsed_ms"],
  }


# --- user state (the only thing still in SQLite) ---


def _progress_entry(pid, a, attempt_run_count, run_count, solves) -> dict:
  """One problem's dynamic state. The client joins this onto the static catalog.

  `solves` is EVERY solved attempt (ascending), not just the latest: the stats
  minimum-elapsed fold, the stats per-day sets and lesson "ever solved" all need
  more than the latest attempt (after a Retake the latest attempt is unsolved,
  but the lesson must stay complete).
  """
  return {
      "id": pid,
      **_attempt_fields(a),
      "attemptRunCount": attempt_run_count,
      "runCount": run_count,
      "solves": solves,
  }


def _solves_by_problem(rows) -> dict:
  by_id = {}
  for r in rows:
    by_id.setdefault(r["problem_id"], []).append(
        {"solvedAt": r["solved_at"], "elapsedMs": r["elapsed_ms"]}
    )
  return by_id


@app.get("/api/progress")
def progress():
  """Every problem's dynamic state, in one bundle (three queries, no N+1).

  Includes problems that have runs but no attempt rows, so the client's sum of
  runCount matches SELECT COUNT(*) FROM run, and ids that are no longer in the
  catalog — both are deliberate.
  """
  with db.connect() as conn:
    attempts = db.latest_attempts(conn)
    counts = db.run_counts(conn)
    solves = _solves_by_problem(db.solved_attempts(conn))

  run_counts = {r["problem_id"]: r["n"] for r in counts}
  seen = {a["problem_id"] for a in attempts}
  items = [
      _progress_entry(a["problem_id"], a, a["run_count"],
                      run_counts.get(a["problem_id"], 0),
                      solves.get(a["problem_id"], []))
      for a in attempts
  ]
  items += [
      _progress_entry(pid, None, 0, n, solves.get(pid, []))
      for pid, n in run_counts.items() if pid not in seen
  ]
  return {"problems": items}


@app.get("/api/problem/state")
def problem_state(id: str):
  """One problem's dynamic state + its saved code.

  Never 404s: whether an id exists is now a *content* question, answered by
  catalog.json. An unknown id is simply not-started with no code.
  """
  with db.connect() as conn:
    a = db.latest_attempt_with_run_count(conn, id)
    counts = db.run_counts(conn, id)
    solves = _solves_by_problem(db.solved_attempts(conn, id))
    code = db.get_submission_code(conn, id)

  entry = _progress_entry(
      id, a, a["run_count"] if a else 0,
      counts[0]["n"] if counts else 0, solves.get(id, []),
  )
  return {**entry, "code": code}


@app.post("/api/problem/attempt/start")
def start_attempt(id: str):
  """Start (or Retake) — insert a fresh running attempt."""
  ts = now_iso()
  with db.connect() as conn:
    db.insert_attempt(conn, id, ts)
  return {"ok": True}


@app.post("/api/problem/attempt/pause")
def pause_attempt(id: str):
  with db.connect() as conn:
    a = db.latest_attempt(conn, id)
    if a and a["running_since"] and a["solved_at"] is None:
      add = round(_delta_ms(a["running_since"], _now_dt()))
      db.pause_attempt(conn, a["id"], add)
  return {"ok": True}


@app.post("/api/problem/attempt/resume")
def resume_attempt(id: str):
  with db.connect() as conn:
    a = db.latest_attempt(conn, id)
    if a and a["running_since"] is None and a["solved_at"] is None:
      db.resume_attempt(conn, a["id"], now_iso())
  return {"ok": True}


@app.put("/api/problem/code")
def save_code(payload: CodePayload):
  ts = now_iso()
  with db.connect() as conn:
    db.upsert_submission(conn, payload.id, payload.code, ts)
  return {"ok": True, "updatedAt": ts}


@app.get("/api/problem/runs")
def list_runs(id: str, limit: int = 50):
  with db.connect() as conn:
    rows = db.list_run_rows(conn, id, limit)
  return [_run_dict(r) for r in rows]


@app.post("/api/problem/runs")
def create_run(payload: RunPayload):
  all_passed = 1 if payload.failed == 0 and payload.total > 0 else 0
  ts = now_iso()
  with db.connect() as conn:
    a = db.latest_attempt(conn, payload.id)
    attempt_id = a["id"] if a else None
    run_id = db.insert_run(
        conn, payload.id, payload.code, payload.passed, payload.failed,
        payload.total, payload.durationMs, all_passed, ts, attempt_id,
    )
    # Finalize the solve time on the active attempt.
    if all_passed and a and a["solved_at"] is None:
      extra = round(_delta_ms(a["running_since"], _now_dt())) if a["running_since"] else 0
      db.finalize_solve(conn, a["id"], ts, a["accumulated_ms"] + extra)
    row = db.get_run(conn, run_id)
  return _run_dict(row)
