"""Coding-trainer API — user state only.

No auth. Every state endpoint resolves the calling browser through
user.current_user() (a cookie today, a token claim once auth exists), and that
id is the DynamoDB partition key of every row it reads or writes: a request can
only reach its own state, and two browsers keep two independent histories.

The knowledge content is NOT served from here: it is static JSON under
app/public/data (generated by build_content.py) that the browser fetches and
indexes into its own in-memory SQLite. What is left is the
state that content can't be: saved code, test runs and timed attempts, read
through /api/progress and /api/problem/state and written by the endpoints below.

POST /api/problem/runs is the one piece of real domain logic still on the
server: it derives all_passed and finalizes the solve on the server clock.

Problems are identified by their path-based id (e.g. "maximum-subarray" or
"CTCI/1.1-is-unique"). Ids can contain "/", so id-specific endpoints take the id
as a query parameter or request-body field rather than a path segment.
"""

from contextlib import asynccontextmanager
from datetime import datetime, timezone

import db
from fastapi import Depends, FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from user import current_user


@asynccontextmanager
async def lifespan(_app: FastAPI):
  db.init_db()
  yield


app = FastAPI(title="Coding Trainer API", lifespan=lifespan)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


def now_iso() -> str:
  return datetime.now(timezone.utc).isoformat()


# Every state endpoint takes this, so the id is resolved and validated on the
# way in and then handed to the db layer, which uses it as the partition key.
USER = Depends(current_user)


class CodePayload(BaseModel):
  id: str
  code: str


class RunPayload(BaseModel):
  id: str
  code: str
  passed: int
  failed: int
  total: int
  durationMs: float


def _run_dict(r) -> dict:
  return {
      "id": r["id"],
      "problemId": r["problem_id"],
      "passed": r["passed"],
      "failed": r["failed"],
      "total": r["total"],
      "durationMs": r["duration_ms"],
      "allPassed": bool(r["all_passed"]),
      "createdAt": r["created_at"],
      "code": r["code"],
  }


@app.get("/api/health")
def health():
  return {"ok": True}


# --- attempts / timing ---


def _now_dt() -> datetime:
  return datetime.now(timezone.utc)


def _delta_ms(iso: str, now: datetime) -> float:
  return (now - datetime.fromisoformat(iso)).total_seconds() * 1000


def _attempt_fields(a) -> dict:
  """Status + timing from the latest attempt.

  `a` is either the latest attempt row or None (no attempt) — the latter means
  "not-started". This is the single source of truth for the derived status; the
  client's `progress` table stores what this returns and never re-derives it.
  """
  if a is None or a["started_at"] is None:
    return {
        "status": "not-started",
        "startedAt": None,
        "accumulatedMs": 0,
        "runningSince": None,
        "solvedAt": None,
        "elapsedMs": None,
    }
  return {
      "status": "solved" if a["solved_at"] else "started",
      "startedAt": a["started_at"],
      "accumulatedMs": a["accumulated_ms"],
      "runningSince": a["running_since"],
      "solvedAt": a["solved_at"],
      "elapsedMs": a["elapsed_ms"],
  }


# --- user state (the only thing stored server-side) ---


def _progress_entry(pid, a, attempt_run_count, run_count, solves) -> dict:
  """One problem's dynamic state. The client joins this onto the static catalog.

  `solves` is EVERY solved attempt (ascending), not just the latest: the stats
  minimum-elapsed fold, the stats per-day sets and lesson "ever solved" all need
  more than the latest attempt (after a Retake the latest attempt is unsolved,
  but the lesson must stay complete).
  """
  return {
      "id": pid,
      **_attempt_fields(a),
      "attemptRunCount": attempt_run_count,
      "runCount": run_count,
      "solves": solves,
  }


def _solves(attempts) -> list:
  """The solve log of one problem's attempts, oldest first.

  A solve is just an attempt with solved_at set — there is no solves table —
  and the attempt lists below are already in ULID (chronological) order, so the
  filter preserves it. The folds over these entries have order-dependent
  tie-breaks, hence the explicit note.
  """
  return [
      {"solvedAt": a["solved_at"], "elapsedMs": a["elapsed_ms"]}
      for a in attempts if a["solved_at"]
  ]


@app.get("/api/progress")
def progress(user: str = USER):
  """Every problem's dynamic state, in one bundle (two queries, no N+1).

  Includes problems that have runs but no attempt rows, so the client's sum of
  runCount matches the number of stored runs, and ids that are no longer in the
  catalog — both are deliberate.

  The attempts query returns *every* attempt of the user, not the latest per
  problem: DynamoDB has no top-N-per-group, so the fold happens here. That is
  cheap because attempt rows are a few scalars each — unlike run rows, which
  carry a code blob and are deliberately never read in this path.
  """
  attempts = db.all_attempts(user)
  run_counts = dict(db.run_counts(user))

  by_problem = {}
  for a in attempts:  # ascending by (problem_id, ULID), so the last one wins
    by_problem.setdefault(a["problem_id"], []).append(a)

  items = [
      _progress_entry(pid, rows[-1], rows[-1]["attempt_run_count"],
                      run_counts.get(pid, 0), _solves(rows))
      for pid, rows in by_problem.items()
  ]
  items += [
      _progress_entry(pid, None, 0, n, [])
      for pid, n in run_counts.items() if pid not in by_problem
  ]
  return {"problems": items}


@app.get("/api/problem/state")
def problem_state(id: str, user: str = USER):
  """One problem's dynamic state + its saved code.

  Never 404s: whether an id exists is now a *content* question, answered by
  catalog.json. An unknown id is simply not-started with no code.
  """
  attempts = db.problem_attempts(user, id)
  code, run_count = db.get_submission(user, id)

  a = attempts[-1] if attempts else None
  entry = _progress_entry(
      id, a, a["attempt_run_count"] if a else 0, run_count, _solves(attempts),
  )
  return {**entry, "code": code}


@app.post("/api/problem/attempt/start")
def start_attempt(id: str, user: str = USER):
  """Start (or Retake) — insert a fresh running attempt."""
  db.insert_attempt(user, id, now_iso())
  return {"ok": True}


@app.post("/api/problem/attempt/pause")
def pause_attempt(id: str, user: str = USER):
  a = db.latest_attempt(user, id)
  if a and a["running_since"] and a["solved_at"] is None:
    add = round(_delta_ms(a["running_since"], _now_dt()))
    db.pause_attempt(user, a["sk"], add)
  return {"ok": True}


@app.post("/api/problem/attempt/resume")
def resume_attempt(id: str, user: str = USER):
  a = db.latest_attempt(user, id)
  if a and a["running_since"] is None and a["solved_at"] is None:
    db.resume_attempt(user, a["sk"], now_iso())
  return {"ok": True}


@app.put("/api/problem/code")
def save_code(payload: CodePayload, user: str = USER):
  ts = now_iso()
  db.upsert_submission(user, payload.id, payload.code, ts)
  return {"ok": True, "updatedAt": ts}


@app.get("/api/problem/runs")
def list_runs(id: str, limit: int = 50, user: str = USER):
  return [_run_dict(r) for r in db.list_run_rows(user, id, limit)]


@app.post("/api/problem/runs")
def create_run(payload: RunPayload, user: str = USER):
  all_passed = 1 if payload.failed == 0 and payload.total > 0 else 0
  ts = now_iso()
  a = db.latest_attempt(user, payload.id)
  # Three writes here and a fourth below, none of them atomic — db.insert_run()
  # documents exactly what drifts if one of them fails.
  row = db.insert_run(
      user, payload.id, payload.code, payload.passed, payload.failed,
      payload.total, payload.durationMs, all_passed, ts,
      a["sk"] if a else None,
  )
  # Finalize the solve time on the active attempt.
  if all_passed and a and a["solved_at"] is None:
    extra = round(_delta_ms(a["running_since"], _now_dt())) if a["running_since"] else 0
    db.finalize_solve(user, a["sk"], ts, a["accumulated_ms"] + extra)
  return _run_dict(row)
