"""Per-browser identity: the one place a request's user id is resolved.

This is NOT authentication. The id is generated by the browser with
crypto.randomUUID() and travels in a plain, non-HttpOnly cookie, so anyone can
set it to someone else's value and read that state. It exists so user state can
be *scoped* to a browser — and so that when real auth does arrive, only
current_user() changes: it reads a verified token claim instead of the cookie,
and every caller stays exactly as it is.

The value comes from the client and is destined to become a storage key, so it
is validated here before anyone sees it: canonical UUID shape, fixed length,
otherwise 400.
"""

import re

from fastapi import Cookie, HTTPException

COOKIE_NAME = "user_id"

# crypto.randomUUID() emits the canonical 8-4-4-4-12 lowercase hex form. Anchored
# and fixed-width, so this bounds the length as well as the shape; the explicit
# length check below keeps that bound obvious (and cheap) at the call site.
UUID_LEN = 36
UUID_RE = re.compile(
    r"\A[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-"
    r"[0-9a-fA-F]{4}-[0-9a-fA-F]{12}\Z"
)


def current_user(user_id: str | None = Cookie(default=None, alias=COOKIE_NAME)) -> str:
  """The calling browser's id, or 400.

  A missing cookie is rejected rather than falling back to a shared default:
  the fallback would quietly merge every cookie-less caller into one bucket —
  and this value is the DynamoDB partition key of every row they read or write.
  The frontend writes the cookie before it issues its first request, so in the
  app a missing cookie means something is actually wrong.

  Returned lowercased so ids that differ only in hex case are one identity and
  not two adjacent storage keys.
  """
  if user_id is None:
    raise HTTPException(status_code=400, detail=f"missing {COOKIE_NAME} cookie")
  if len(user_id) != UUID_LEN or not UUID_RE.match(user_id):
    raise HTTPException(status_code=400, detail=f"malformed {COOKIE_NAME} cookie")
  return user_id.lower()
