// Fetches the static knowledge content generated by backend/build_content.py
// and served from public/data. Pure fetching — no React, no user state.
import type { Catalog, LessonsContent, ProblemContent } from './types'

const DATA = '/data'

// Thrown when a content file is missing or unreadable. Callers map it to the
// page's "not found" state.
export class ContentNotFound extends Error {
  constructor(path: string) {
    super(`content not found: ${path}`)
    this.name = 'ContentNotFound'
  }
}

async function loadJson<T>(path: string): Promise<T> {
  // public/ assets are unhashed, so a stale copy would survive a rebuild.
  const res = await fetch(path, { cache: 'no-cache' })
  if (!res.ok) throw new ContentNotFound(path)
  const text = await res.text()
  try {
    return JSON.parse(text) as T
  } catch {
    // Under an SPA catch-all rewrite a missing file comes back as 200 text/html;
    // without this the page would spin forever waiting on a promise that
    // resolved to garbage.
    throw new ContentNotFound(path)
  }
}

// Every memo's "forget what you cached" hook, so clearContentCache() below can
// drop them all at once without each memo needing its own exported resetter.
const forget: (() => void)[] = []

// Memoize the in-flight promise so concurrent callers share one request, and
// drop the memo if it rejects so a transient failure isn't cached for the
// session. /api/progress is dynamic and is never memoized.
function memoize<T>(load: () => Promise<T>): () => Promise<T> {
  let cached: Promise<T> | null = null
  forget.push(() => {
    cached = null
  })
  return () => {
    if (!cached) {
      const p = load()
      cached = p
      p.catch(() => {
        if (cached === p) cached = null
      })
    }
    return cached
  }
}

// Deliberately NOT memoized: db.ts's syncContent() refetches this on every
// navigation and compares generatedAt to decide whether the content was
// rebuilt under the open tab — which is precisely the check a memo would
// defeat. The fetch is conditional (cache: 'no-cache' above), so an unchanged
// build costs a 304 with no body.
export function loadCatalog(): Promise<Catalog> {
  return loadJson<Catalog>(`${DATA}/catalog.json`)
}

export const loadLessons = memoize(() => loadJson<LessonsContent>(`${DATA}/lessons.json`))

// Encode per segment: ids can contain "/" (CTCI/1.1-is-unique) and a flat
// encodeURIComponent would turn it into %2F, which static hosts normalize
// inconsistently.
function problemUrl(id: string): string {
  return `${DATA}/problems/${id.split('/').map(encodeURIComponent).join('/')}.json`
}

const problems = new Map<string, Promise<ProblemContent>>()

export function loadProblem(id: string): Promise<ProblemContent> {
  const cached = problems.get(id)
  if (cached) return cached
  const p = loadJson<ProblemContent>(problemUrl(id))
  problems.set(id, p)
  p.catch(() => {
    if (problems.get(id) === p) problems.delete(id)
  })
  return p
}

// Drop every cached content response, so the next load refetches. Called by
// db.ts when catalog.json's generatedAt changes. The per-problem Map has to go
// with the rest: clearing only the catalog would invert the staleness bug —
// the list would show the new build while an already-visited detail page kept
// serving its pre-rebuild JSON.
export function clearContentCache(): void {
  for (const reset of forget) reset()
  problems.clear()
}
