export type TestStatus = 'pass' | 'fail' | 'error'

export interface TestResult {
  name: string
  status: TestStatus
  message: string
}

export interface RunRecord {
  id: number
  problemId: string
  passed: number
  failed: number
  total: number
  durationMs: number
  allPassed: boolean
  createdAt: string
  code: string
}

export type ProblemStatus = 'not-started' | 'started' | 'solved'

// --- static content (generated by backend/build_content.py) ---

// A catalog.json row: the fields the list page filters and renders on.
export interface CatalogProblem {
  id: string
  title: string
  difficulty: string
  tags: string[]
  position: number
}

export interface Catalog {
  generatedAt: string
  count: number
  problems: CatalogProblem[] // already in position order — never sort it
}

// One problems/<id>.json file. Title/difficulty/tags are duplicated from the
// catalog so a detail page renders without loading it.
export interface ProblemContent {
  id: string
  title: string
  difficulty: string
  tags: string[]
  sources: string[]
  description: string
  hint: string
  primaryFunction: string
  starter: string
  solution: string
  tests: string
}

// A lessons.json entry (bodies are inlined — the whole file is ~36 KB).
export interface LessonContent {
  id: string
  title: string
  topic: string
  position: number
  body: string
  exercises: string[]
}

export interface LessonsContent {
  generatedAt: string
  lessons: LessonContent[]
}

// --- user state (GET /api/progress) ---

export interface Solve {
  solvedAt: string
  elapsedMs: number | null
}

// One problem's dynamic state. `solves` lists EVERY solved attempt ascending,
// which is more than the latest: after a Retake the latest attempt is unsolved
// but the problem is still "ever solved".
export interface ProgressEntry extends AttemptState {
  id: string
  runCount: number // runs across all attempts
  solves: Solve[]
}

export interface ProgressBundle {
  problems: ProgressEntry[]
}

export interface ProblemState extends ProgressEntry {
  code: string | null
}

// --- curriculum / lessons ---

export interface LessonSummary {
  id: string
  title: string
  topic: string
  position: number
  exerciseCount: number
  solvedCount: number
  done: boolean
}

export interface LessonsResponse {
  lessons: LessonSummary[]
}

export interface LessonExercise {
  id: string
  title: string
  difficulty: string
  status: ProblemStatus
}

export interface LessonDetail {
  id: string
  title: string
  topic: string
  body: string
  exercises: LessonExercise[]
}

// --- stats ---

export interface DifficultyStat {
  difficulty: string
  solved: number
  total: number
}

export interface TagStat {
  tag: string
  solved: number
  total: number
}

export interface TimeStat {
  avgMs: number | null
  bestMs: number | null
  count: number
}

export interface DifficultyTimeStat extends TimeStat {
  difficulty: string
}

export interface FastestSolve {
  id: string
  title: string
  difficulty: string
  elapsedMs: number
}

export interface RecentSolve {
  id: string
  title: string
  difficulty: string
  solvedAt: string
  elapsedMs: number | null
}

export interface ProblemRef {
  id: string
  title: string
  difficulty: string
}

export interface StatsResponse {
  solvedCount: number
  totalProblems: number
  totalRuns: number
  totalTimeMs: number
  streak: { current: number; longest: number }
  byDifficulty: DifficultyStat[]
  byTag: TagStat[]
  solveTime: { overall: TimeStat; byDifficulty: DifficultyTimeStat[] }
  fastest: FastestSolve[]
  daily: { date: string; count: number }[]
  recent: RecentSolve[]
  inProgress: ProblemRef[]
}

// Status + timing from the latest attempt (returned by both list and detail).
export interface AttemptState {
  status: ProblemStatus
  startedAt: string | null
  accumulatedMs: number
  runningSince: string | null // ISO while the timer runs; null while paused/solved
  solvedAt: string | null
  elapsedMs: number | null // final solve time (ms)
  attemptRunCount: number // Run-Tests clicks in the latest attempt
}

// Row in the paginated catalog list.
export interface ProblemListItem extends AttemptState {
  id: string
  title: string
  difficulty: string
  tags: string[]
}

export interface ProblemPage {
  items: ProblemListItem[]
  total: number
  page: number
  pageSize: number
}

export interface Facet {
  value: string
  count: number
}

export interface Facets {
  difficulties: Facet[]
  tags: Facet[]
}

export type StatusFilter = 'all' | ProblemStatus

// What the detail page renders: the static content joined with this user's
// saved code and latest-attempt state.
export interface ProblemView extends ProblemContent, AttemptState {
  code: string | null
}

// Full problem definition + this user's saved code + latest-attempt state.
export interface ProblemFull extends AttemptState {
  id: string
  title: string
  difficulty: string
  tags: string[]
  sources: string[]
  description: string
  hint: string | null
  starter: string
  solution: string
  tests: string
  code: string | null
}
